### ISSUE TITLE
As LeadDev, I'd like the project with a R package structure

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#1]
## Validation

- [x] The checks (`devtools::check()`) of the projects show that the repository is recognised as a proper R package  
  ![image](https://user-images.githubusercontent.com/21193866/219671519-26f72aff-c253-4c5e-9385-1261391b081f.png)

- [x] Continuous Integration is up and ready. Everything is green means that the package checks are good, the unit test report is ready, the documentation website is ready   
    - :link: Link to Actions: https://github.com/balglave/FishMap/actions  
![image](https://user-images.githubusercontent.com/21193866/219674588-7b5b5b1f-21d7-46b4-affc-b565781ac55a.png)

- [x] pkgdown website is online: https://balglave.github.io/FishMap  
![image](https://user-images.githubusercontent.com/21193866/221832143-a7118b74-5083-4afb-b397-5e58d9d55980.png)

- [x] The link between GitHub and codecov.io is ready and will allow to read the code coverage reports for each commit: https://app.codecov.io/gh/balglave/FishMap/  
![image](https://user-images.githubusercontent.com/21193866/221832058-a3f8bd27-5343-44c3-82ab-f170d53bb74c.png)

- [x] The value of coverage and the link to codecov is available on the Home page of the project 
    + Link to home page (See readme below): https://github.com/balglave/FishMap
![image](https://user-images.githubusercontent.com/21193866/221832914-cec85a27-4672-4b8e-849e-d4fcd819d99c.png)

## Tech

Could you please address this two points blocked: 

- [x] **1. I need the pkgdown website to be online.**

    - Go to: https://github.com/balglave/FishMap/settings/pages
    -  Set up gh-pages to be deployed as on this image
 
![image](https://user-images.githubusercontent.com/21193866/219675580-a2ae4f4b-879a-4f10-bc1b-95a9f031d4e0.png)

- [x] **2. I need codecov to be connected to the repository**
    - Go to : https://app.codecov.io/
    - Connect with your GitHub account
    - You may be able to follow this link : https://app.codecov.io/gh/balglave/FishMap/new
        - Or find your repo in the list and activate it
    - Follow step 1 and step 2. Because GitHub Actions is already setup

**Comment by statnmap** [comment]
@balglave Could you please unblock me by addressing the 2 points in the "Blocked" section above : https://github.com/balglave/FishMap/issues/1#issue-1589087436 ?  
Thank you.

**Comment by balglave** [comment]
Je valide.
