### ISSUE TITLE
As dev, I'd like to know if the outputs of the model are the same between our machine and the client's machine

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#15]
As a Dev, I would like to make sure that the output of the functions and graphics are similar between my environment and the client's environment. 

## Client - Validation

- [x] Outputs between devs and clients are compared, and potential differences are shown in the vignette "Verify model reproducibility"

![Image](https://user-images.githubusercontent.com/54443785/224093050-afc6fb48-c7e6-4dad-8633-d933b1049edf.png)

=> https://balglave.github.io/FishMap/articles/check_model_reproducibility.html

- [x] I understand that outputs are the same in 2 different runs on ThinkR machine, without the need for a tolerance  

![image](https://user-images.githubusercontent.com/21193866/224959912-34d645ee-86dc-410f-a87a-5155a89db5fb.png)

=> https://balglave.github.io/FishMap/articles/check_model_reproducibility.html#checking-seed-reproducibility

- [x] I understand that next outputs are compared one by one with a tolerance of `1e-4`  

![image](https://user-images.githubusercontent.com/21193866/224960582-878e5c45-c3a4-40cd-aa4f-be9d33b7368a.png)
  
![image](https://user-images.githubusercontent.com/21193866/224960382-f0b8d97a-f3d3-483f-9861-12c7a7792872.png)

=> https://balglave.github.io/FishMap/articles/check_model_reproducibility.html#create-contrast-function

- [x] I understand that there are comparisons between ThinkR and Baptiste outputs on one hand, and ThinkR and Juliette outputs on the other hand

![image](https://user-images.githubusercontent.com/21193866/224960710-4bc4542c-f79a-4592-9c0f-c1d334436e4c.png)

=> Starting from here: https://balglave.github.io/FishMap/articles/check_model_reproducibility.html#contrasting-converge_output-rds-output  

- [x] If I have questions about some outputs, I list my questions as a comment of this issue. It may help detail future comparisons.  

## Dev-tech

- [x] A Rmd properly divided
- [x] See if {waldo} can help in the comparison

## What was Blocked

We need to verify that the outputs on your machine are the same as ours, while using the same "seed", so that we can properly define the future unit tests.

Please 
- [x] Validate issue https://github.com/balglave/FishMap/issues/9
- [x] Please follow instructions in this vignette: https://balglave.github.io/FishMap/articles/execute-main.html
    - [x] You'll find the source of this vignette in file "vignette/execute-main.Rmd"
- [x] Please zip the output directory and upload it in a comment below (if GitHub allows it)

**Comment by JCasemajor** [comment]
[outputs_fishmap.zip](https://github.com/balglave/FishMap/files/10897028/outputs_fishmap.zip)

**Comment by statnmap** [comment]
@balglave could you please also address this issue.  
It seems that you do not have the same versions of spatial packages as you did not face the problem there #12 .  
Hence, before you update everything, could you please create the "outputs.zip" so that we make sure all original conditions are met in our future unit tests.  
Thank you

**Comment by dagousket** [comment]
hi @balglave , I have amended `main.R` so it sources the scripts from their correct location. This issue is ready for you to take in charge.

**Comment by balglave** [comment]
[shared.zip](https://github.com/balglave/FishMap/files/10912068/shared.zip)

**Comment by JCasemajor** [comment]
Je valide.

**Comment by balglave** [comment]
Je valide
