### ISSUE TITLE
[feat] As user, I'd like the 'main.R' file to be presented as a vignette of the package

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#18]
As user, I'd like the 'main.R' file to be presented as a vignette of the package, so that it is run at each check of the package

## Client - Validation 

+ [x] To achieve this ticket, we faced problems with checks on MacOS and Windows in the Continuous Integration: Compilation of cpp source cannot be achieved for now. We chose to ignore this problem to continue the development of the package, as at least, it works on Linux. However, we opened a blocked issue, so that you can decide what to do, please have a look at it, after the validation of the present issue: #24  

![image](https://user-images.githubusercontent.com/21193866/223380676-33ab2f9f-c217-49f1-890e-e0b7c8d71bfc.png)

+ [x] Due to obsolete spatial packages use, we changed `raster::crs()` to `sp::CRS()` in file "inst/original_scripts/domain_mesh_spde.R", following recommandation of Juliette C. This leads to extra questions about spatial dependencies that you will find in this blocked issue: #12 

![image](https://user-images.githubusercontent.com/21193866/223381129-f756b9e7-bb4d-4474-8a5e-1e474ae929fc.png)

+ [x] the outputs of original 'main.R' are shown in a vignette in the {pkgdown} website

![image](https://user-images.githubusercontent.com/54443785/223373292-b6355e8a-be56-4926-93a0-e51884d2aa20.png)

=> [https://balglave.github.io/FishMap/articles/running-fishmap.html](https://balglave.github.io/FishMap/articles/running-fishmap.html)

+ [x] 'main.R' is now a flat file in the "dev/flat_main.Rmd". All modifications of the code will now take place in the flat files.

![Screenshot 2023-03-07 at 09 50 35](https://user-images.githubusercontent.com/54443785/223371514-b79410dd-3209-4647-8da9-1793fda3d03b.png)

=> https://github.com/balglave/FishMap/blob/main/dev/flat_main.Rmd

+ [x] Original scripts are sourced from "inst/"

![Screenshot 2023-03-07 at 09 55 43](https://user-images.githubusercontent.com/54443785/223372856-57274331-d3e0-48de-a2f7-d3be0465c0e1.png)

=> https://github.com/balglave/FishMap/tree/main/inst/original_scripts

+ [x] Original datasets needed are loaded from "inst/"

![Screenshot 2023-03-07 at 09 52 12](https://user-images.githubusercontent.com/54443785/223372245-fd68594c-5367-43cd-95f4-c023cfa573ff.png)

=> https://github.com/balglave/FishMap/tree/main/inst/original_data/Solea_solea

## Dev - Tech

+ [x] copy main.R to "dev/flat_main.Rmd", block by block => 1 part for 1 anonymous chunk `{r}`
+ [x] Get file in "inst/"
+ [x] Get data needed in "inst/"
+ [x] In 0-dev_history.Rmd 
    + `devtools::check()`
    + `devtools::check(args = list("--no-vignette"))`
+ [x] Create `pkgdown::build_site()`
+ [ ] ~Delete "main.R"~

**Comment by dagousket** [comment]
`main.R` is still necessary for issue #15

**Comment by dagousket** [comment]
{raster} raises a CI failure :

![image](https://user-images.githubusercontent.com/54443785/223125053-55f9680b-2025-45c6-93b3-11dab71cb87e.png)

**Comment by balglave** [comment]
Je valide

**Comment by JCasemajor** [comment]
Je valide
