### ISSUE TITLE
[feat] As client, I'd like part 1 of the flat_main to be a documented and tested function

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#19]
As client, I'd like part 1 of the flat_main to be a documented and tested function, so that I can guarantee its outputs, whatever changes in the packages

## Client - Validation 

+ [x] There is a function with all parameters needed, which returns outputs of part 1 as one object (a list)

![image](https://user-images.githubusercontent.com/54443785/223698718-c3729241-56d5-473a-b89d-c4e249720d2f.png)
...
![image](https://user-images.githubusercontent.com/54443785/223698796-1005859a-5154-4dbb-bb66-d0e72fe1ec60.png)

=> [https://github.com/balglave/FishMap/blob/main/R/fm_load_data.R](https://github.com/balglave/FishMap/blob/main/R/fm_load_data.R)

+ [x] This function is tested, at least to be sure there no error (it tests that rds file outputs exists)

![image](https://user-images.githubusercontent.com/54443785/223699049-184a6170-d478-4bde-aabd-3e6c37bae251.png)

=> [https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_load_data.R](https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_load_data.R)

+ [x] This function is used in the main vignette

![image](https://user-images.githubusercontent.com/54443785/223699684-8e1cf23f-7425-45c4-a9b5-d2e65c97d998.png)

=> [https://balglave.github.io/FishMap/articles/running-fishmap.html](https://balglave.github.io/FishMap/articles/running-fishmap.html)

## Dev - Tech

+ [x] Transform code of the anonymous chunk as a function: Use the RStudio tool to do it:
   + Select code as is (without `function()`) => Go to Menu "Code" > Extract Function. Give the function a name, all variables should be extracted. You can try with a simple example like: `print(toto)`
+ [x] Get all necessary outputs as a list()
    + Discover outputs by running the next chunk, so that we only get necessary outputs.
+ The lists of outputs
```r
outputs <- ma_function_prep(  return(list(nom = contenu, nom2 = contenu2)))
saveRDS(outputs, "outputs_part1.rds") # in FISHMAP_OUTPUT
toto <- outputs[["toto"]]
```

**Comment by dagousket** [comment]
The refactoring of part1 raises the following warning in the `devtools::check()` at the moment :
```
W  checking whether package ‘FishMap’ can be installed (27.6s)
   Found the following significant warnings:
     Warning: replacing previous import ‘dplyr::union’ by ‘raster::union’ when loading ‘FishMap’
     Warning: replacing previous import ‘dplyr::select’ by ‘raster::select’ when loading ‘FishMap’
     Warning: replacing previous import ‘dplyr::intersect’ by ‘raster::intersect’ when loading ‘FishMap’
     Warning: replacing previous import ‘raster::extract’ by ‘tidyr::extract’ when loading ‘FishMap’
```
This is due to using full library imports in the function specification in order to cover for imports required in sourced files. The refactoring of the source files will resolve this warning by specifying the function imported.

**Comment by balglave** [comment]
D'accord avec Juliette. Ces arguments sont necessaires dans 'domain_mesh_spde.R'.

**Comment by statnmap** [comment]
Merci. Nous avons ouvert un ticket dédié pour ces paramètres particuliers: https://github.com/balglave/FishMap/issues/34  
Vous aurez un autre ticket ensuite pour lister tous les autres paramètres que vous jugez nécessaires.   

Je ferme le présent ticket si c'est ok pour vous.

**Comment by JCasemajor** [comment]
Je valide

**Comment by balglave** [comment]
Je valide
