### ISSUE TITLE
As client, I'd like to follow the steps of development

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#2]
## Validation

- [x] I know there is a wiki that lists all sources of information  for the project
    - :link: https://github.com/balglave/FishMap/wiki
   ![image](https://user-images.githubusercontent.com/21193866/219667839-67b45e51-e5b8-4a0a-af84-8f8742ec9829.png)
- [x] I know that I can see my assignments in the following Board: https://github.com/users/balglave/projects/1/views/1
- [x] I know I can find the documentation website of the package: https://balglave.github.io/FishMap

**Comment by balglave** [comment]
Je valide
