### ISSUE TITLE
[feat] As user, I'd like to have a scheme of the use of the package

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#20]
[feat] As client, I'd like to have a scheme of the project, so that I can see how the package works

## Client - Validation 

+ [x] I understand that the figure will be updated all along the development of the package
+ [x] A JSON file exists in the project to re-create the state of the scheme by importing on https://excalidraw.com/
    + The file is in "dev/user_scheme_of_use.json"
    + URL: https://github.com/balglave/FishMap/blob/main/dev/user_scheme_of_use.json
+ [x] A general figure shows the pipeline to use of the package in the Readme of the project: https://github.com/balglave/FishMap/blob/main/README.md
+ [x] A general figure shows the pipeline to use of the package in the Home page of the documentation website: https://balglave.github.io/FishMap/

![image](https://user-images.githubusercontent.com/21193866/223090504-a0dd3116-1753-4a9e-a31a-ea81e40eb67c.png)

## Dev - Tech

+ [x] Create an excalidraw raw object that can be stored in the project as JSON
+ [x] Export the figure to show in the main vignette

**Comment by JCasemajor** [comment]
Je valide.

**Comment by balglave** [comment]
Je valide
