### ISSUE TITLE
[ci] As dev, I'd like {FishMap} to run on Windows and MacOS installations

### ISSUE THREAD

**Issue by dagousket** [balglave/FishMap#24]
[ci] As dev, I'd like FishMap to run on a Windows and MacOS installations so that CI does not fail anymore and the package can be used on multiple OS.

## Problem

Currently, the CI is broken for Windows and MacOS. This is due to the compilation of cpp TMB files.

In view of the success criteria for the mission, it was important for you to ensure that the package could be used on the different OS. For the proper development of the package over time, you must be able to fix the CI on both platforms.

=> You are expected to arbitrate on this issue:

- Either we spend time to make sure the CI runs and the files compile well but this time spent will be at the expense of the package.  **The estimated time to fix this problem may be half a day.**
- Or we leave it as is, continuing development while CI keeps working on Linux, and we explore this problem later, if we have time during the mission. _Indeed, what happens in CI is sometimes difficult to address due to this non-interactive environment_
- Or we leave it to you to look into this on your own, based on your experience with the TMB installation.

=> Please add your answer as a comment of this issue

## Client - Validation

What we want to achieve, once this problem is solved:

- To have a complete pipeline to check if the package can be installed and checked on all operating systems.

## Dev - Tech

+ [ ] See if there is something in [{TMBtools}](https://github.com/mlysy/TMBtools) that we missed to address the problem

Error from CI on `check-r-package` from windows latest install
```
--- re-building 'running-fishmap.Rmd' using rmarkdown
C:\rtools40\ucrt64\bin\g++.exe
C:\ProgramData\Chocolatey\bin\g++.exe
C:\Strawberry\c\bin\g++.exe
C:\ProgramData\Chocolatey\bin\gdb.exe
C:\Strawberry\c\bin\gdb.exe
C:\R\bin\x64\Rterm.exe
C:\Program Files\R\R-4.2.2\bin\x64\Rterm.exe
g++ -std=gnu++11  -I"C:/R/include" -DNDEBUG -I"D:/a/_temp/Library/TMB/include" -I""  -DTMB_SAFEBOUNDS -DTMB_EIGEN_DISABLE_WARNINGS -DLIB_UNLOAD=R_unload_model  -DTMB_LIB_INIT=R_init_model  -DCPPAD_FRAMEWORK    -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O1 -g -c C:/Users/runneradmin/AppData/Local/Temp/RtmpQRJiUm/Rinst50033f62039/FishMap/model.cpp -o C:/Users/runneradmin/AppData/Local/Temp/RtmpQRJiUm/Rinst50033f62039/FishMap/model.o
In file included from C:/Users/runneradmin/AppData/Local/Temp/RtmpQRJiUm/Rinst50033f62039/FishMap/model.cpp:2:
D:/a/_temp/Library/TMB/include/TMB.hpp:78:10: fatal error: Eigen/Dense: No such file or directory
   78 | #include <Eigen/Dense>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [C:/R/etc/x64/Makeconf:2[60](https://github.com/balglave/FishMap/actions/runs/4345189050/jobs/7589553603#step:6:62): C:/Users/runneradmin/AppData/Local/Temp/RtmpQRJiUm/Rinst50033f[62](https://github.com/balglave/FishMap/actions/runs/4345189050/jobs/7589553603#step:6:64)039/FishMap/model.o] Error 1
Quitting from lines 173-279 (running-fishmap.Rmd)
```

**Comment by balglave** [comment]
I would choose the 2nd option. Keep going on Linux and if you have time, come back later on this issue.

**Comment by statnmap** [comment]
I close this issue. It is mentioned in the Agenda, so that we can re-open it if needed: https://github.com/balglave/FishMap/wiki/Agenda#m5---make-it-run-on-windows-and-macos
