### ISSUE TITLE
As dev, we would like Cervan to be added as contributor of the project

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#25]
As leaddev, we would like Cervan to be added as contributor of the project so that he can manage the project

## Problem

@cervangirard is not listed as contributor of the GitHub repository, which prevents him to manage code, wiki, and issues properly.   

=> Could you please add him ?

- Go to Settings > Collaborators and Team > Add People > @cervangirard > Role: Write

![image](https://user-images.githubusercontent.com/21193866/223390299-2df231b0-355c-4733-8ecc-b500727fef3d.png)

## Client - Validation 

Once this problem is addressed, 

+ [x] Cervan is able to edit an issue in the GitHub repository

## Dev - Tech

+ [ ]

**Comment by balglave** [comment]
I added Cervan.

**Comment by statnmap** [comment]
Thanks. We validate this issue.
