### ISSUE TITLE
[FEAT] As client, I'd like "part 2 : fit model" of the flat_main to be a documented and tested function

### ISSUE THREAD

**Issue by Cervangirard** [balglave/FishMap#27]
As client, I'd like _part 2 : fit model_ of the flat_main to be a documented and tested function, so that I can guarantee its outputs, whatever changes in the packages

## Client - Validation 

+ [x] There is a function with all parameters needed, which returns outputs of _part 2 : fit model_ as one object (a list)

![Image](https://user-images.githubusercontent.com/54443785/223733833-cc6342d4-6713-4f90-85c1-24f46a8c1451.png)
...

![Image](https://user-images.githubusercontent.com/54443785/223733921-8e0c59c2-1873-48fa-8e4e-06df98e141ab.png)

=> [https://github.com/balglave/FishMap/blob/main/R/fm_fit_model.R](https://github.com/balglave/FishMap/blob/main/R/fm_fit_model.R)

+ [x] This function is tested, at least to be sure there no error (it tests that rds file outputs exists)

![Image](https://user-images.githubusercontent.com/54443785/223734107-fba700ed-384a-4215-9779-35e5262d9d19.png)

=> [https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_fit_model.R](https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_fit_model.R)

+ [x] This function is used in the main vignette

![image](https://user-images.githubusercontent.com/54443785/223736086-685c69cf-7999-4c66-b53c-2ffe528d60ac.png)

=> [https://balglave.github.io/FishMap/articles/running-fishmap.html](https://balglave.github.io/FishMap/articles/running-fishmap.html)

## Dev - Tech

+ [x] Transform code of the anonymous chunk as a function: Use the RStudio tool to do it:
   + Select code as is (without `function()`) => Go to Menu "Code" > Extract Function. Give the function a name, all variables should be extracted. You can try with a simple example like: `print(toto)`
+ [x] Get all necessary outputs as a list()
    + Discover outputs by running the next chunk, so that we only get necessary outputs.
+ The lists of outputs
```r
outputs <- ma_function_prep(  return(list(nom = contenu, nom2 = contenu2)))
saveRDS(outputs, "outputs_part1.rds") # in FISHMAP_OUTPUT
toto <- outputs[["toto"]]
```

**Comment by dagousket** [comment]
`{fusen}` example chunks for the functions of the main vignette do not have the `ex-` flag so they will be run in series and share their outputs. This will avoid to re-run `fm_load_data()` for the example chunk of `fm_fit_model()`

**Comment by balglave** [comment]
Je valide

**Comment by JCasemajor** [comment]
Je valide.
