### ISSUE TITLE
[feat] As client, I'd like part 3 : "generate graphs" of the flat_main to be a documented and tested function

### ISSUE THREAD

**Issue by Cervangirard** [balglave/FishMap#30]
As client, I'd like _part 3 : generate graphs_ of the flat_main to be a documented and tested function, so that I can guarantee its outputs, whatever changes in the packages

## Client - Validation 

+ [x] There is a function with all parameters needed, which returns outputs of _part 3:generat_graphs_ as one object (a list)

![image](https://user-images.githubusercontent.com/54443785/223761611-f1656a53-161b-4b85-bcd3-98bed826496e.png)
...
![image](https://user-images.githubusercontent.com/54443785/223761670-4b909d7e-057a-432f-8021-a91defee94da.png)

=> [https://github.com/balglave/FishMap/blob/main/R/fm_generate_graphs.R](https://github.com/balglave/FishMap/blob/main/R/fm_generate_graphs.R)

+ [x] This function is tested, at least to be sure there no error (it tests that rds file outputs exists)

![image](https://user-images.githubusercontent.com/54443785/223761925-cd284a66-2cc9-40c5-b6dc-750aec8ab024.png)

=> [https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_generate_graphs.R](https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_generate_graphs.R)

+ [x] This function is used in the main vignette

![image](https://user-images.githubusercontent.com/54443785/223762889-59f2d77a-b5e3-4c40-a36e-be73c7fcaa84.png)

=> [https://balglave.github.io/FishMap/articles/running-fishmap.html](https://balglave.github.io/FishMap/articles/running-fishmap.html)

+ [x] The general code coverage of the package is currently: 84.5%
    + [x] The detail by main function is shown in this screenshot

![image](https://user-images.githubusercontent.com/21193866/223771541-9d436b8b-47da-4026-bdd7-faf00998b125.png)

=> Link: https://app.codecov.io/gh/balglave/FishMap/tree/main/R

## Dev - Tech

+ [x] Transform code of the anonymous chunk as a function: Use the RStudio tool to do it:
   + Select code as is (without `function()`) => Go to Menu "Code" > Extract Function. Give the function a name, all variables should be extracted. You can try with a simple example like: `print(toto)`
+ [x] Get all necessary outputs as a list()
    + Discover outputs by running the next chunk, so that we only get necessary outputs.
+ The lists of outputs
```r
outputs <- ma_function_prep(  return(list(nom = contenu, nom2 = contenu2)))
saveRDS(outputs, "outputs_part1.rds") # in FISHMAP_OUTPUT
toto <- outputs[["toto"]]
```

**Comment by balglave** [comment]
Je valide.

**Comment by JCasemajor** [comment]
Je valide.
