### ISSUE TITLE
As user, I'd like to have more parameters available in function `fm_load_data()`

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#34]
As user, I'd like to have more parameters available in function fm_load_data() so that I can change them easily.

## Client Validation

- [x] `k` is available as parameter in `fm_load_data()` with information

![image](https://user-images.githubusercontent.com/54443785/224962126-c143d097-66a1-4c9d-a72b-ea10e4e705c5.png)

![image](https://user-images.githubusercontent.com/54443785/224962335-2889a6e3-0be1-4a2a-89c6-7fa56467fc32.png)

=> https://balglave.github.io/FishMap/reference/fm_load_data.html

- [x] `grid_xmin, grid_xmax, grid_ymin, grid_ymax` are available as parameter in `fm_load_data()`

![image](https://user-images.githubusercontent.com/54443785/224962126-c143d097-66a1-4c9d-a72b-ea10e4e705c5.png)

![image](https://user-images.githubusercontent.com/54443785/224962335-2889a6e3-0be1-4a2a-89c6-7fa56467fc32.png)

=> https://balglave.github.io/FishMap/reference/fm_load_data.html

- [x] I understand I will have the opportunity to add other parameters with other default, after I answer this issue: https://github.com/balglave/FishMap/issues/43

## Dev - Tech

I would suggest putting the setup of the spatial domain (grid_xmin, grid_xmax, grid_ymin, grid_ymax) as parameter for the fm_load_data function as the user will probably change it according to its data (i.e. if we want to study Celtic sea instead of the Bay of Biscay)

_Originally posted by @JCasemajor in https://github.com/balglave/FishMap/issues/19#issuecomment-1460518536_

**Comment by balglave** [comment]
Je valide

**Comment by JCasemajor** [comment]
Je valide.
