### ISSUE TITLE
[doc] As user, I would like to have up-to-date and clear documentation

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#35]
[doc] As user, I would like to have up-to-date and clear documentation so that I know which command to execute to properly run FishMap.

## Client - Validation 

+ [x] The scheme on the Reame file is updated with the new function names

![image](https://user-images.githubusercontent.com/54443785/224988474-61466b88-9c63-4678-8d76-a301e0122a4f.png)

=> https://balglave.github.io/FishMap/

+ [x] The vignettes intended for devs now have a `dev-` prefix

![image](https://user-images.githubusercontent.com/54443785/224988538-d1c17d30-97dc-4556-91cb-bf232d2a06b1.png)

=> https://balglave.github.io/FishMap/

+ [x] The vignette showing how to execute `main.R` now clearly explain how to edit the `.Renviron` file

![image](https://user-images.githubusercontent.com/54443785/224994218-b9aba10b-2a9a-4b85-b03e-8cdc1410b725.png)

=> https://balglave.github.io/FishMap/articles/dev-execute-main.html

## Dev - Tech

- Update dev schematic on Readme, starting from the json file in the dev folder
- Rename vignette with a 'dev-' prefix
- Mention the use of `usethis::edit_r_environ()` to execute main.R

**Comment by balglave** [comment]
Je valide

**Comment by JCasemajor** [comment]
Je valide.
