### ISSUE TITLE
As a client, I would like the `fm_fit_model()` function to be tested on what is returned by the function

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#36]
As a client, I would like the `fm_fit_model()` function to be tested on what is returned by the function, so that I am warned if there are differences in outputs while changing other functions or while updating package dependencies.

## Client - Validation 

+ [x] Testing the result of `fm_fit_model` is a list
![image](https://user-images.githubusercontent.com/37626302/225257451-cca4fb34-eb45-44c7-909f-0605a4e5e473.png)

+ [x] Testing names of the list return by `fm_fit_model` to have stable behaviour
![image](https://user-images.githubusercontent.com/37626302/225257664-298aa860-82bc-4b19-981d-a3f71c6e89cd.png)

+ [x] Testing types inside the list return by `fm_fit_model` 
![image](https://user-images.githubusercontent.com/37626302/225257817-34c08061-ceeb-4150-b216-c5f5b14a9168.png)

+ [x] Unit tests are documented for the future unit test report
      - All tests have a description tag

+ [x] The code coverage is adapted to this function
![image](https://user-images.githubusercontent.com/37626302/225258232-e8c03c4f-819e-46f7-a787-41809abcb781.png)

## Dev - Tech

- Préparer les test unitaires pour fit_model : Cervan
    - Variable envt (k) pour tests plus précis: Cervan
- Pour chaque `expect_*(), il est nécessaire d'ajouter un `@description` juste au-dessus pour le rapport de {testdown} qu'on livrera. Exemple: https://thinkr-open.github.io/testdown/test-hello-world.html

**Comment by JCasemajor** [comment]
Je valide.

**Comment by balglave** [comment]
Je valide
