### ISSUE TITLE
[ci] Temporary hide windows and macos CI checks

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#41]
As dev, I'd like to Temporary hide windows and macos CI checks, so that the checks are green and do not pollute mailboxes waiting for a proper fix

## Client - Validation 

+ [x] GitHub Actions Workflow are commented for windows and Macos, but All Linux stay in  

![image](https://user-images.githubusercontent.com/21193866/224990756-f317742c-dcee-42c0-a12b-76419054a1ce.png)

=> https://github.com/balglave/FishMap/blob/main/.github/workflows/R-CMD-check.yaml

+ [x] Checks are green on the home page of the project  

![image](https://user-images.githubusercontent.com/21193866/225023707-fa72971f-ce9c-4711-ba02-6f30223ffeb1.png)

=> https://github.com/balglave/FishMap

## Dev - Tech

+ [ ]

**Comment by balglave** [comment]
Je valide

**Comment by JCasemajor** [comment]
Je valide.
