### ISSUE TITLE
As user, I'd like to have all asked parameters as entry of the `fm_load_data()` correctly documented

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#43]
As user, I'd like to have all parameters possible as entry of the functions correctly documented, so that I can adapt the model to my datasets

## Client - Validation 

- [x] `fm_load_data()` allows to change parameters `species`, `fleet`, `fitted_data`, `survey_data_file`, `vmslogbook_data_file`, `study_domain_file`, `year_start`, `year_end`, `month_start`, `month_end`, `time_step`, `k`, `grid_xmin`, `grid_xmax`, `grid_ymin`, `grid_ymax` and `seed`

<img width="544" alt="image" src="https://user-images.githubusercontent.com/54443785/226568965-a0748f2c-b321-4e39-83aa-5d86f538566e.png">

=> https://balglave.github.io/FishMap/reference/fm_load_data.html

- [x]  All params of `fm_load_data()`  are documented

<img width="804" alt="image" src="https://user-images.githubusercontent.com/54443785/226569114-e414c97a-a0e8-477b-8c79-6f4e20fc5ced.png">

=> https://balglave.github.io/FishMap/reference/fm_load_data.html 
=> https://github.com/balglave/FishMap/blob/main/man/fm_load_data.Rd

- [x] The parameters `time_step` and `fitted_data` have a proper default value

<img width="436" alt="Screenshot 2023-03-21 at 10 45 37" src="https://user-images.githubusercontent.com/54443785/226569792-f3e585cc-e5bf-4110-af98-befe481af8b7.png">

<img width="791" alt="image" src="https://user-images.githubusercontent.com/54443785/226574688-622bd075-13b4-4a33-ba82-66fbfda7e1a5.png">

<img width="784" alt="image" src="https://user-images.githubusercontent.com/54443785/226574730-f9a0ec53-2f95-40f1-91f4-fe9323f2f08e.png">

=> https://balglave.github.io/FishMap/reference/fm_load_data.html 

- [x] An error is raised if incorrect parameters are provided

We specify possible values with `match.atg()` :
![image](https://user-images.githubusercontent.com/54443785/226585528-af2b3eb1-9d66-478d-8d12-258ea6d4e99e.png)

=> https://github.com/balglave/FishMap/blob/main/R/fm_load_data.R

`match.arg()` returns an error for incorrect values :
![image](https://user-images.githubusercontent.com/54443785/226579040-de48a491-841a-4a56-b216-550c1c4eae4d.png)

The error behavior is integrated in the test of the function :
![image](https://user-images.githubusercontent.com/54443785/226574959-720400ef-3ae2-4258-9d0f-d680bd74eb77.png)

=> https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_load_data.R

- [x] non-default values are now specified for running examples and tests

In **test** :

![image](https://user-images.githubusercontent.com/54443785/226575109-d21d4bba-34b7-44db-a84c-95d2edc75f14.png)

=> https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_load_data.R

In **examples** :

![image](https://user-images.githubusercontent.com/54443785/226575337-792bc555-7049-482f-ad41-6de3d61322e6.png)

=> https://github.com/balglave/FishMap/blob/main/vignettes/user-running-fishmap.Rmd

## Dev - Tech

+ [x] retrieve info from excel file from client https://github.com/balglave/FishMap/files/10982407/functions_parameters.xlsx
+ [x] adjust `fm_load_data()` inputs according to excel file
+ [x] add a parameter `seed = 29510`
+ [x] add `withr::local_seed(seed = seed)` at the beginning of function
+ [x] use `match.arg()` at the beginning of `fm_load_data()` to restrict parameters to expected values
+ [x] specify non-default parameters in test and examples 
+ [x] use full path inputs (no system.file call in function `load_data()`)
+ [x] add test to verify match.arg behavior
+ [x] create same ticket for `fm_fit_model()` once this one is in pre-val

### Client inputs

To be able to write the correct documentation, could you please list all parameters that you would like to see in the parameters of the functions, separated by family and by function

To do so, we will ask you to list the parameters as a 'roxygen' documentation for each function.  
_If you think it would be better to move some parameters in the `fm_fit_model()`, it is still time to ask._

You can look at the current documentation of each function to see what already exists: https://balglave.github.io/FishMap/reference/index.html

We would need this information:

- Function among `fm_load_data()`, `fm_fit_model()`, `fm_generate_graphs()`
- Name of the parameter
- Type
- Description
- Default value (can be empty)

You can give this information as a csv/Excel file if you want to, or any other mean that suits you

**Comment by JCasemajor** [comment]
Je valide.

**Comment by balglave** [comment]
Je valide
