### ISSUE TITLE
As user, I'd like to see the difference between vignettes for developers usage, and vignettes for users

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#44]
As user, I'd like to see the difference between vignettes for developers usage, and vignettes for users, so that I know what I can read, depending on my role

## Client - Validation 

+ [x] In the pkgdown website, I can see the difference between users and dev vignettes

![image](https://user-images.githubusercontent.com/54443785/225256733-76417f3d-2834-444e-8ab6-d4058a3d0e90.png)

=> https://balglave.github.io/FishMap/index.html

+ [x] I know that if I want to have access to the vignette locally, I need to build them during installation

![image](https://user-images.githubusercontent.com/54443785/225256840-8193a04b-7e9f-4b18-afdf-01c2f3acf10d.png)

=> https://balglave.github.io/FishMap/index.html

+ [x] When the user searches the vignette locally with `vignette(package = "FishMap")`, they can see the different vignettes (if they built the package with vignettes)

Installing FishMap locally, with vignette :
![Screenshot 2023-03-15 at 12 12 31](https://user-images.githubusercontent.com/54443785/225292874-a90b1747-6a8e-46b3-8722-8c43ffefbdc1.png)

Searching for vignette :
![Screenshot 2023-03-15 at 09 34 51](https://user-images.githubusercontent.com/54443785/225253372-60b4885c-c41f-4601-8e27-4e4f7fc9292e.png)

## Dev - Tech

+ [x] Name the thumbnails "dev-" in title, only for dev vignettes
+ [x] Name the thumbnails "user-" in title, only for users vignettes
    + I guess "Running FishMap" is a users' vignette 
+ [x] Add a new line in the Readme to inform the user they can access the vignettes locally with `remotes::install_github("balglave/FishMap", build_vignettes = TRUE)`

**Comment by JCasemajor** [comment]
Je valide.
