### ISSUE TITLE
As client, I'd like function `fm_load_data()` to be properly tested

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#45]
As client, I'd like function `fm_load_data()` to be properly tested, so that I am warned if there are differences in outputs while changing other functions or while updating package dependencies.

## Client - Validation 

+ [x] There is a unit test for each output of the function. The unit test is properly chosen depending on the size of the output, so that it does not make a too heavy package.

* testing output file is found after saving output
![image](https://user-images.githubusercontent.com/54443785/225576628-e6f2bae2-d734-4e4a-bb09-62a2ebcf0eb9.png)

* testing output is a list with the correct variables names
![image](https://user-images.githubusercontent.com/54443785/225576317-3fa8647d-b16d-44a3-9ec3-55fd6b7fc2da.png)
...

* testing type of each list element
![image](https://user-images.githubusercontent.com/54443785/225576391-9cd20db4-2390-43a5-9ee7-1c91951477b9.png)
...

* testing the tmp dir created when generating the mesh
![image](https://user-images.githubusercontent.com/54443785/225576531-c9c67ab7-eafe-438a-b6a7-0020956f9227.png)

* testing the full object against a previously saved run
   * the comparison is done with a previous run using as default k=0.25 to prevent large output files
![image](https://user-images.githubusercontent.com/54443785/225577909-7656b2e5-3954-471f-8180-10b57dce693f.png)
   * the comparison used `expect_equal()` which guarantee the exact numerical match between the runs
![image](https://user-images.githubusercontent.com/54443785/225576711-c2c98fcb-d0b0-46de-ada7-1924973018f6.png)

=> https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_load_data.R

+ [x] Unit tests are documented for the future unit test report

All unit test are associated to a `@description` tag (see. screenshots above)

=> https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_load_data.R

+ [x] The code coverage is adapted to this function

![Screenshot 2023-03-16 at 10 48 31](https://user-images.githubusercontent.com/54443785/225579598-9ba9a0e0-d391-4a6d-8cfa-6e345e2da5a7.png)

=> https://app.codecov.io/gh/balglave/FishMap?search=&displayType=list

+ [x] I know how to update the "expected outputs" in case I voluntarily update the functions of the package, which lead to different outputs

![image](https://user-images.githubusercontent.com/54443785/225579795-e1ebf4c4-8de8-4b15-b869-41f1db1d90b1.png)

=> https://github.com/balglave/FishMap/blob/main/dev/0-dev_history.Rmd

## Dev - Tech

- [ ] Unit tests of function 1 (0.5j): Swann
    - Outputs can be stored in "inst/". Can be used for examples.
    - Outputs can be stored in "tests/testthat/ , but you will need `if (file.exists())` (=> relative paths) for use in {fusen} flat files. 
- [ ] There is a code, documented for devs that tells how and what to copy from the output folder (var. env.), to "inst/" or "testthat/" as appropriate, to store the "expected outputs" of the tests
- [x] Pour chaque `expect_*(), il est nécessaire d'ajouter un `@description` juste au-dessus pour le rapport de {testdown} qu'on livrera. Exemple: https://thinkr-open.github.io/testdown/test-hello-world.html

**Comment by balglave** [comment]
Je valide

**Comment by JCasemajor** [comment]
Je valide.
