### ISSUE TITLE
As client, i'd like to have a stable behaviour for outputs of the `fm_fit_model` function

### ISSUE THREAD

**Issue by Cervangirard** [balglave/FishMap#47]
As client, i'd like to have a stable behaviour for outputs of the `fm_fit_model` function so that I am warned if there are differences in outputs while changing other functions or while updating package dependencies

## Client - Validation 

After this is unblocked we plan to validate these points:

+ [ ] There is a unit test for each result of the function. The unit test is properly chosen depending on the size of the output, so that it does not make a too heavy package.
    + [ ] `time.step_df_output`
    + [ ] `loc_x`
    + [ ] `report_output` with only a look at the spatial predictions (S_x) and total biomass (total_abundance).
    + [ ] `samp_process_output`

## Dev - Tech

+ [ ] Save only what is needed for the outputs
+ [ ] Units tests for each result

- [ ] => We suggest to only look at the spatial predictions (S_x) and total biomass (total_abundance). You should get it by doing fm_model_results$report$S_p and fm_model_results$report$total_abundance.

## Problem

We want to write stable unit tests that can, over time, identify real differences in the model's output. Checking on the entire model results can cause the test to fail on very small differences. Here is an example:

![image](https://user-images.githubusercontent.com/37626302/225256276-b680f533-e90b-497d-962a-e8876d33ac29.png)

 - **What are the essential elements of the list of `fm_fit_model` that are stable over time if the parameters are unchanged?**
- **For each sub-element of the list, what are the elements to be tested?**

**Comment by balglave** [comment]
We suggest to only look at the spatial predictions (S_x) and total biomass (total_abundance). You should get it by doing fm_model_results$report$S_p and fm_model_results$report$total_abundance.

**Comment by Cervangirard** [comment]
Thanks. We close this ticket because the tests pass for a model with a small k and a short period. We will reprocess this issue later with a more consistent model
