### ISSUE TITLE
As dev, I would like to have a function without calling source in the fm_fit_model function

### ISSUE THREAD

**Issue by Cervangirard** [balglave/FishMap#48]
As dev, I would like to have a function without calling source in the fm_fit_model function so that i can test the part inside the sourced file.

## Client - Validation 

+ [x] Have function that replace `source`

![Image](https://user-images.githubusercontent.com/37626302/225294127-30d54ea1-318b-41c0-aaaa-121dcadd4e6a.png)

+ [x] This function sould be documented but we only give the same name for parameter (is not exported function)

![Image](https://user-images.githubusercontent.com/37626302/225295249-3f6fe7c4-f90e-44be-b456-22604858330c.png)

+ [x] This function sould be proprely tested

![Image](https://user-images.githubusercontent.com/37626302/225295354-d66392f7-2557-40c9-806a-97ca34691250.png)

+ [x] Run a local test to ensure that we have obtained the same results as with the source (this test is inside `test-fm_fit_model.R`)

![image](https://user-images.githubusercontent.com/37626302/225317272-ef7a2e42-5e17-4078-a658-6037000dcb18.png)
![image](https://user-images.githubusercontent.com/37626302/225317413-425d9d39-147a-40d3-ba0f-ebd9145727fc.png)

## Dev - Tech

+ [ ] make a function for `source(file.path(script_folder,"build_data_params_map.R"), local=TRUE)`
+ [ ] take care about the parameters and the outputs

**Comment by JCasemajor** [comment]
Je valide.

**Comment by balglave** [comment]
Je valide
