### ISSUE TITLE
As dev, I'd like to easily update my expected test outputs

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#51]
As dev, I'd like to easily update my expected test outputs

## Client - Validation 

+ [x] I know where are the intermidate rdata to update them : `inst`
![image](https://user-images.githubusercontent.com/37626302/226887505-627be317-0093-496d-830b-7ab17e0ad43c.png)
+ [x] A documentation (vignette) to explain how to update the outputs used for tests (and examples)
https://balglave.github.io/FishMap/articles/dev_how_to_maintain_my_tests_and_examples.html
![image](https://user-images.githubusercontent.com/37626302/226888435-68b833e2-bb3f-4611-b0d8-e362dcf1e6a9.png)
+ [x] A specific implementation in the tests files that detects the state to update or not
![image](https://user-images.githubusercontent.com/37626302/226887804-0ba266ba-853e-46ca-b163-e5261f60d4d7.png)
+ [x] The tests allow for a bigger model implementation to be tested, behind a env. variable
![image](https://user-images.githubusercontent.com/37626302/226887946-81759623-4a42-4cd3-84c1-a701c6122ba7.png)
+ [x] Have information of versions of packages for developpers to pass Unit tests
![image](https://user-images.githubusercontent.com/37626302/226888186-d8669341-c16d-4ace-a0d8-4e4e8ecf1aea.png)

## Dev - Tech

+ [x] Create a flat file "dev-how to maintain my tests and examples"
+ [x] Explain how and where the output files are storage
+ [x] Explain how we implement the difference between small and big tests
+ [x] Explain why examples should be only used small outputs
+ [x] Find a way to expose versions of packages for the developper

**Comment by balglave** [comment]
Je valide
