### ISSUE TITLE
[load_data] Update unit tests of `fm_load_data()` to store properly the intermediate outputs

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#55]
As dev, i'd like to have outputs of `fm_load_data` proprely stored so that i'll reuse the result for `fm_fit_model`

## Client - Validation 

+ [x] Check that we find 1 RDS files in `inst` : one for `fm_load_data` with low resolution

<img width="1248" alt="Screenshot 2023-03-21 at 12 03 05" src="https://user-images.githubusercontent.com/54443785/226587727-a5ea0e89-ba6f-42c1-a643-69c3c81f9ff5.png">

=> https://github.com/balglave/FishMap/tree/main/inst/examples

+ [x] Check that tests and examples are adapted with this data in `inst`

* test of `fm_load_data()` used saved output of `fm_load_data()` to compare expexted result:

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/54443785/226590115-7675cb30-1e9c-42b3-85c6-325e8009c314.png">

<img width="717" alt="image" src="https://user-images.githubusercontent.com/54443785/226590360-781d547b-2842-4305-8354-d8d00633f755.png">

=> https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_load_data.R

* test of `fm_fit_model()` used saved output of `fm_load_data()` :
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/54443785/226588801-6edee522-3916-4921-940d-1e554a237840.png">

=>  https://github.com/balglave/FishMap/blob/main/tests/testthat/test-fm_fit_model.R

* example of `fm_fit_model()` used saved output of `fm_load_data()` :

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/54443785/226589230-da9a0570-323e-469f-8f8f-a9c5635c9aee.png">

=> https://github.com/balglave/FishMap/blob/main/vignettes/dev-fit-model.Rmd

+ [x] Have a specific flat file for fm_load_data

<img width="927" alt="Screenshot 2023-03-21 at 12 04 53" src="https://user-images.githubusercontent.com/54443785/226588105-8a1ccfbe-96b9-42ca-8f02-27fbb94c303d.png">

=> https://github.com/balglave/FishMap/blob/main/dev/flat_fm_load_data.Rmd

+ [x] Update the schema

<img width="824" alt="image" src="https://user-images.githubusercontent.com/54443785/226590586-48ff1d98-fde5-46ac-b1e1-b92ccdc1df0b.png">

=> https://balglave.github.io/FishMap/

## Dev - Tech

+ [x] Please, be inspired by this PR : https://github.com/balglave/FishMap/pull/54
+ [x] Put the function in separate flat file
+ [x] For each the main function, save the outputs in `inst`.
   - In the test part of your flat file, adapte this example 
```
  fm_data_inputs <- fm_load_data(k = 0.25, month_start = 11, month_end = 11)
  # Update expected outputs here
  if (Sys.getenv("FISHMAP_UPDATE_TEST_OUTPUTS") == "TRUE") {
    # save output depending if we are in flat or in test
    output_inst_dir <- here::here("inst", "examples")  
    
    if (test_resolution == "small") {
      readr::write_rds(x = fm_data_inputs,
                       file = file.path(output_inst_dir, paste0("part1_output_", test_resolution , ".rds")))
}
```
   - Because it is in inst, you don't need to store again in `tests`
+ [x] For the test part of each function, please read the expected result in inst. 
     - To compare your result
+ [x] Create one result for `fm_load_data`

**Comment by JCasemajor** [comment]
Je valide.
