### ISSUE TITLE
[load_data] Update unit tests of `fm_fit_model()` to store properly the intermediate outputs

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#56]
As dev, i'd like to have outputs of `fm_fit_model` proprely stored so that i'll reuse the result for `fm_graphique`

## Client - Validation 

+ [x] Check that we find 1 RDS files in `inst` : one for `fm_fit_model` with low resolution

![Image](https://user-images.githubusercontent.com/37626302/226357871-6d404165-affb-49fa-8584-925e0fd07217.png)

+ [x] Check that tests and examples adapted with this data in `inst`
![image](https://user-images.githubusercontent.com/37626302/226361921-ff90072e-12ba-4d41-918f-1cfd6c704755.png)

+ [x] Have a specific flat file for `fm_fit_model`

 > https://balglave.github.io/FishMap/articles/dev-fit-model.html

## Dev - Tech

+ [x] For each the main function, save the outputs in `inst`.
   - In the test part of your flat file, adapte this example 
```
  fm_data_inputs <- fm_load_data(k = 0.25, month_start = 11, month_end = 11)
  # Update expected outputs here
  if (Sys.getenv("FISHMAP_UPDATE_TEST_OUTPUTS") == "TRUE") {
    # save output depending if we are in flat or in test
    output_inst_dir <- here::here("inst", "examples")  
    
    if (test_resolution == "small") {
      readr::write_rds(x = fm_data_inputs,
                       file = file.path(output_inst_dir, paste0("part1_output_", test_resolution , ".rds")))
}
```
   - Because it is in inst, you don't need to store again in `tests`
+ [x] For the test part of each function, please read the expected result in inst. 
     - To compare your result
+ [x] Create one result for `fm_fit_model`

**Comment by JCasemajor** [comment]
Je valide.

**Comment by balglave** [comment]
Je valide
