### ISSUE TITLE
As user, I'd like to have all parameters possible as entry of the function `fm_fit_model()` correctly documented

### ISSUE THREAD

**Issue by dagousket** [balglave/FishMap#63]
As user, I'd like to have all parameters possible as entry of the function `fm_fit_model()` correctly documented, so that I can adapt the model to my datasets

## Client - Validation 

- [x] `fm_fit_model()` allows to change parameters
![image](https://user-images.githubusercontent.com/37626302/226588932-b4372ab0-0bc1-437d-b2b0-49988254c9e8.png)
- [x]  All params of `fm_fit_model()`  are documented
![image](https://user-images.githubusercontent.com/37626302/226589074-8977c870-8c0a-4b68-8f09-ca41d3d8aeb8.png)
- [x] An error is raised if incorrect parameters are provided 
![image](https://user-images.githubusercontent.com/37626302/226584597-a505032d-5554-4249-9cc9-3e5bef981512.png)
- [x] non-default values are now specified for running examples and tests
![image](https://user-images.githubusercontent.com/37626302/226584746-bc69b862-6901-4ff2-b263-0a7a623e8dad.png)

## Dev - Tech

+ [x] retrieve info from excel file from client https://github.com/balglave/FishMap/files/10982407/functions_parameters.xlsx
+ [x] adjust `fm_fit_model()` inputs according to excel file
+ [x] add a parameter `seed = 29510`
+ [x] add `withr::local_seed(seed = seed)` at the beginning of function
+ [x] specify non-default parameters in test and examples

**Comment by balglave** [comment]
Je valide
