### ISSUE TITLE
[fm_load_data] As dev, I would like to have a function for executing the code from `domain_mesh_spde.R`

### ISSUE THREAD

**Issue by dagousket** [balglave/FishMap#66]
As dev, I would like to have a function for executing the code from `domain_mesh_spde.R` in the `fm_load_data function()` so that I can test the part inside this source file.

## Client - Validation 

+ [x] Have a function that replace `source(file.path(script_folder,"domain_mesh_spde.R"), local=TRUE)`

![image](https://user-images.githubusercontent.com/54443785/226898973-bd7cc53d-aa3d-492a-900e-f6c08dccb3bc.png)

=> https://github.com/balglave/FishMap/blob/main/dev/flat_fm_load_data.Rmd

+ [x] This function should be documented with the same params used for `fm_load_data`

* param `k` doc inherits from `fm_load_data()` information :
![Screenshot 2023-03-22 at 13 01 02](https://user-images.githubusercontent.com/54443785/226899234-26274580-868f-4249-b242-4de59658ee82.png)

* other params are specific to the new function and documented inplace :
![Screenshot 2023-03-22 at 13 03 48](https://user-images.githubusercontent.com/54443785/226899778-6488c90d-eb76-4446-b4e5-13bbe92fe20a.png)

=> https://github.com/balglave/FishMap/blob/main/dev/flat_fm_load_data.Rmd

+ [x] This function is covered by unit test

![Screenshot 2023-03-22 at 13 05 27](https://user-images.githubusercontent.com/54443785/226900071-4a695bfb-5b18-47ac-8501-99f4bd9c21f0.png)

=> https://app.codecov.io/gh/balglave/FishMap/blob/main/R/fm_build_domain_mesh_spde.R

+ [x] Run a test on saved outputs to ensure that we have obtained the same results for `fm_load_data()` for runs with source or function calls

* test on saved outputs are successful locally when running `test/testhat/test-fm_load_data.R`:
![Screenshot 2023-03-22 at 12 40 50](https://user-images.githubusercontent.com/54443785/226900864-a6c214d2-3c73-4d57-945d-5993db83e659.png)

* test on saved outputs are successful on CI:
![image](https://user-images.githubusercontent.com/54443785/226901104-b1a96abf-d849-4d38-807f-6ab183c09b13.png)

## Dev - Tech

+ [x] make a function for `source(file.path(script_folder,"domain_mesh_spde.R"), local=TRUE)` in the flat of `fm_load_data`
+ [x] do not export the function as it is only internally used by `fm_load_data()`
+ [x] implement the parameters with `@inheritParams fm_load_data`
+ [x] return the output necessary for `fm_load_data()` as a named list
+ [x] once this ticket is in pre-val, create the same ticket for `shape_sci_data_st.R` and `shape_vmslogbook_data_st.R`

**Comment by dagousket** [comment]
`study_domain_sf` is a variable used within a loop conditioned on `create_mesh == "from_data"` which is not tested in the current state of the fm_load_data() (create_mesh is hardcoded to "from_shapefile")

**Comment by balglave** [comment]
Je valide
