### ISSUE TITLE
As dev, I'd like all unit tests around function `fm_fit_model()` to use tolerance of `1e-4`

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#67]
As dev, I'd like all unit tests around function `fm_fit_model()` to use tolerance of `1e-4`, so that it is robust to small changes of versions of INLA and TMB

## Client - Validation 

+ [x] The implemented tests pass with tolerance of 1e-4 for the function `fm_fit_model`

![image](https://user-images.githubusercontent.com/37626302/226955735-6d58a775-56cb-4044-935d-e5399a0c26c5.png)
![image](https://user-images.githubusercontent.com/37626302/226955947-f4d58c92-30b6-42fc-84c3-376b78adadbf.png)

## Dev - Tech

+ [x] In the unit tests, please change the tolerance

**Comment by balglave** [comment]
Je valide
