### ISSUE TITLE
[feat] As dev, I'd like to be sure that original scripts work

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#7]
As dev, I'd like to be sure that original scripts work so that I can create target values for future unit tests

## Client - Validation 

+ [ ] Detailed doc for the installation of FishMap dependencies (inc. TMB) is present in the README

![image](https://user-images.githubusercontent.com/54443785/221840401-0279a417-245d-4892-9a40-aa70327c2da6.png)

=> Readme on Home page of the project: https://github.com/balglave/FishMap  
=> Readme: Home page on the website: https://balglave.github.io/FishMap/

+ [ ] ThinkR can reproduce maps outputs for _Solea solea_ in the Bay of Biscay from the original script

![image](https://user-images.githubusercontent.com/54443785/221830804-c9d2e182-d371-4fc6-9bf1-675b8271b3ff.png)

![image](https://user-images.githubusercontent.com/54443785/221831396-10ab4d1b-b8d8-4b17-85f9-ce4d8a17c4d9.png)

![image](https://user-images.githubusercontent.com/54443785/221831453-aab0a02d-b980-40ba-b774-34d92eb8d5ed.png)

![image](https://user-images.githubusercontent.com/54443785/221831497-9b4319cc-a048-4299-a377-6ebc7a3d86fe.png)

+ [ ] Some parts are identified as futures parts of the project (1 part = 1 flat file), with potential functions

![Screenshot 2023-02-28 at 12 29 35](https://user-images.githubusercontent.com/54443785/221841570-2e012726-b6e9-44dc-976d-818962fda8d2.png)

+ [ ] DESCRIPTION file list extra dependencies required for non-CRAN package: INLA

![image](https://user-images.githubusercontent.com/54443785/222120832-cf9a9e22-7718-42cf-9014-83fca0f13cbe.png)
=> [https://github.com/balglave/FishMap/commit/174b76479d3baf362c0e3e600a2a24cd500a58bf#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231c](https://github.com/balglave/FishMap/commit/174b76479d3baf362c0e3e600a2a24cd500a58bf#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231c)

+ [ ] yaml file for CI have INLA installation extra dependency url specified

![image](https://user-images.githubusercontent.com/54443785/222120171-cc0826cb-c7db-43ac-9eaa-6c698a2fde1f.png)
=> [https://github.com/balglave/FishMap/commit/174b76479d3baf362c0e3e600a2a24cd500a58bf#diff-9c940e8ad2b7bc4c26ec3da57b94bc00e73e2166cfed689da51a4c59bcc0a310](https://github.com/balglave/FishMap/commit/174b76479d3baf362c0e3e600a2a24cd500a58bf#diff-9c940e8ad2b7bc4c26ec3da57b94bc00e73e2166cfed689da51a4c59bcc0a310)

+ [ ] CI is green for all OSs

![image](https://user-images.githubusercontent.com/54443785/222121881-d7ebd344-04e8-4e98-95a3-b5fa8d719579.png)

+ [ ] Conflicts with main branch were addressed  

=> [https://github.com/balglave/FishMap/commit/174b76479d3baf362c0e3e600a2a24cd500a58bf#diff-7c669b130405476e22842e0725fbb6ed23edf2994abbca6a101e5bbce706b2c8](https://github.com/balglave/FishMap/commit/174b76479d3baf362c0e3e600a2a24cd500a58bf#diff-7c669b130405476e22842e0725fbb6ed23edf2994abbca6a101e5bbce706b2c8)

## Dev - Tech

+ [x] Execute code from "main.R"
+ [x] Define globally where to cut the scripts for future flats and functions

**Comment by dagousket** [comment]
warnings in `source("dev/r_scripts_orig/domain_mesh_spde.R")`
requires to change {raster} to {terra}

```
Warning messages:
1: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=geocent +R=1 +units=m +no_defs +type=crs
2: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
3: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=1 +no_defs +type=crs
4: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
5: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
6: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
7: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
8: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
9: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=geocent +R=1 +units=m +no_defs +type=crs
10: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
11: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=1 +no_defs +type=crs
12: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
13: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
14: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
15: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
16: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
17: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=geocent +R=1 +units=m +no_defs +type=crs
18: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
19: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=1 +no_defs +type=crs
20: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
21: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
22: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
23: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
24: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
25: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=geocent +R=1 +units=m +no_defs +type=crs
26: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
27: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=1 +no_defs +type=crs
28: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
29: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
30: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
31: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
32: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
33: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=geocent +R=1 +units=m +no_defs +type=crs
34: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
35: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=1 +no_defs +type=crs
36: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
37: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
38: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
39: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
40: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
41: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=geocent +R=1 +units=m +no_defs +type=crs
42: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
43: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=1 +no_defs +type=crs
44: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
45: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
46: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
47: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=longlat +R=6378137 +no_defs +type=crs
48: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
49: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded ellps unknown in Proj4 definition: +proj=geocent +R=1 +units=m +no_defs +type=crs
50: In showSRID(SRS_string, format = "PROJ", multiline = "NO",  ... :
  Discarded datum unknown in Proj4 definition
```

**Comment by dagousket** [comment]
for windows only in `main.R`
```
# Add link to path
fixwinpath <- function(){
  PATH <- Sys.getenv("PATH")
  PATH <- paste0(R.home(), "/bin/x64;", PATH)
  PATH <- paste0("c:/Rtools/mingw64/bin;", PATH)
  Sys.setenv(PATH=PATH)
}
fixwinpath()
shell("where g++")
shell("where gdb")
shell("where Rterm")
```

**Comment by balglave** [comment]
Je valide.

**Comment by JCasemajor** [comment]
Je valide.

**Comment by statnmap** [comment]
Bonjour,
Merci pour la validation de ce ticket.
Est-ce que vous pouvez cocher les cases, en plus d'écrire "je valide" pour qu'on soit sûr que vous ayez validé toutes les parties du ticket. 
Merci

**Comment by JCasemajor** [comment]
Bonjour,
J'ai coché les cases plusieurs fois mais lorsque je ferme et ouvre à nouveau le board, les coches ne sont pas maintenues. Est ce qu'il y a une manip particulière que j'aurais manqué pour valider les modifications ?

**Comment by statnmap** [comment]
Si vous cochez trop vite, GitHub n'a pas le temps de se mettre à jour.  
Généralement, il faut cocher, attendre 1 ou 2 sec que l'interface se mette à jour, avant de cocher la case suivante.   
Normalement, votre rôle est "collaborateur", donc vous devriez avoir les droits pour faire les coches.

**Comment by balglave** [comment]
J'ai coche les cases.

**Comment by statnmap** [comment]
I just noticed that if you open the issue from within the Board, the checkboxes do not work properly.  
You need to open the issue as full screen in a new tab: 
- either CRTL + Click from the board to open in a new tab, 
- or click a second time on the title so that the issue opens up in a new page.  
I am sorry, I did not notice this before.
