### ISSUE TITLE
[fm_load_data] As dev, I would like to have a function for executing the code from `shape_sci_data_st.R`

### ISSUE THREAD

**Issue by dagousket** [balglave/FishMap#70]
As dev, I would like to have a function for executing the code from `shape_sci_data_st.R` in the `fm_load_data()` function so that I can test the part inside this source file.

## Client - Validation 

+ [x] Have a function that replace `source(file.path(script_folder,"shape_sci_data_st.R"), local=TRUE)`

![image](https://user-images.githubusercontent.com/54443785/226950972-6195722c-633f-48e6-9c1b-aa2e8bd602bd.png)

=> https://github.com/balglave/FishMap/blob/main/dev/flat_fm_load_data.Rmd

+ [x] This function has documented parameters

![image](https://user-images.githubusercontent.com/54443785/226951295-6705be9e-14f0-47f1-90af-28234d6f9e71.png)
(no parameters are inherited from `fm_load_data()`)

=> https://github.com/balglave/FishMap/blob/main/R/fm_shape_sci_data_st.R

+ [x] This function is covered by unit test

![Screenshot 2023-03-22 at 16 18 48](https://user-images.githubusercontent.com/54443785/226951979-6124704e-be67-42bf-aaa7-55adc83a89c1.png)

=> https://app.codecov.io/gh/balglave/FishMap/blob/main/R/fm_shape_sci_data_st.R

+ [x] Run tests on saved outputs to ensure that we have obtained the same results for `fm_load_data()` for runs with source or function calls

* locally executing `tests/testthat/test-fm_shape_sci_data_st.R` completes successfully :
![image](https://user-images.githubusercontent.com/54443785/226956733-ac4da4bb-add2-4364-b863-e45879b6ab31.png)
(warnings correspond to the `Discarded xx unknown in Proj4 definition` due to the use of the old package {raster}, cf [closed issue 7](https://github.com/balglave/FishMap/issues/7#issuecomment-1447850502))

* executing CI pipeline completes successfully :
![image](https://user-images.githubusercontent.com/54443785/226952896-c9a9a775-e273-4eb2-a5cc-c47cf7a8bb58.png)

## Dev - Tech

+ [x] make a function for `source(file.path(script_folder,"shape_sci_data_st.R"), local=TRUE)` in the flat of `fm_load_data`
+ [x] do not export the function as it is only internally used by `fm_load_data()`
+ [ ] ~implement the parameters with `@inheritParams fm_load_data`~ -> no shared param with `fm_load_data()`
+ [x] return the output necessary for `fm_load_data()` as a named list
+ [x] once this ticket is in pre-val, create the same ticket for `shape_vmslogbook_data_st.R`

**Comment by dagousket** [comment]
One `if` statement of the `fm_shape_sci_data_st()` function is currently not tested as the parameter `scientific_observation` is currently hardcoded to `"CPUE"` in `fm_load_data()`

**Comment by JCasemajor** [comment]
Je valide.

**Comment by balglave** [comment]
Je valide
