### ISSUE TITLE
As user, i'd like to have the function `fm_load_data` works with object not a path to a file

### ISSUE THREAD

**Issue by Cervangirard** [balglave/FishMap#79]
As user, i'd like to have the function `fm_load_data` works with object not a path to a file so that users can load there own data

## Client - Validation 

+ [ ] Les fonctions sont dites "pure"
    - elles ne modifient pas l'env global de l'utilisateur car elles n'utilisent plus `load()`
   
![image](https://user-images.githubusercontent.com/54443785/229466460-38937c35-b40f-4906-a2bb-b7e5e15651b2.png)

=> https://github.com/balglave/FishMap/blob/main/R/fm_load_data.R

+ [ ] L'utilisateur est libre de choisir son format de données car elles sont lu avant l'exécution de la fonction
    - les données en entrées sont des data.frame plutôt que des chemin vers des fichiers Rdata

![image](https://user-images.githubusercontent.com/54443785/229465555-beac887a-7176-4aa2-bb91-988d4927c08a.png)

   - les examples chargent les données depuis un fichier Rds avant de lancer la fonction

![image](https://user-images.githubusercontent.com/54443785/229466318-b17e25cf-2be8-45e8-bcc4-4f2a0fb7a1b8.png)

=> https://github.com/balglave/FishMap/blob/main/R/fm_load_data.R

+ [ ] les entrées des données sont pré-visualisée dans la vignette d'exemple

![image](https://user-images.githubusercontent.com/54443785/229473846-0fa809b1-67f3-4a1a-accf-06309d970236.png)

![image](https://user-images.githubusercontent.com/54443785/229473910-c67cca4c-8b92-4e32-819b-005c0962ca1f.png)

=> https://balglave.github.io/FishMap/articles/user-running-fishmap.html

+ [ ] les Rdata et scripts originaux ont été retirés du pkg

![Screenshot 2023-04-03 at 11 26 55](https://user-images.githubusercontent.com/54443785/229469538-71572895-1730-4b3f-82f2-9be25dd5c434.png)

=> https://github.com/balglave/FishMap/tree/main/inst/original_data/Solea_solea
(les anciennes fonctions sont conservées dans `dev/r_script_orig/function`)
=> https://github.com/balglave/FishMap/tree/main/dev/r_scripts_orig

## Dev - Tech

+ [x] Lire les objets pour comprendre le contenu
+ [x] Objet R est lu en entrée et pas de load
+ [x] Transformer les Rdata en Rds et utiliser des read_rds
+ [x] Faire en sorte que la fonction utilise des objets
+ [x] Retirer les `_files` et les `load` dans les fonctions
+ [x] Retirer les sources et system.files qui ne sont plus nécessaires
+ [x] supprimer les scripts originaux
+ [x] mettre a jour globals.R

**Comment by balglave** [comment]
Je valide
