### ISSUE TITLE
As dev, I'd like to check low resolution model reproducibility

### ISSUE THREAD

**Issue by JCasemajor** [balglave/FishMap#89]
As dev, I would like to be able to execute the content of the article "Check low resolution model reproducibility".

## Dev

+ [ ] I can find a vignette explaining me how to check low resolution model reproducibility
<img width="846" alt="image" src="https://user-images.githubusercontent.com/79973083/230322229-88c12eb2-974f-4c1f-9411-387778a663ad.png">

+ [ ] I **can't** run [source](https://rdrr.io/r/base/source.html)(here::[here](https://here.r-lib.org//reference/here.html)("dev", "run_main_and_save_output.R")) since the original scripts have been deleted.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/79973083/230329183-8d8a1a7d-e8b2-4e0e-a336-b8e733d600a4.png">

**Comment by Cervangirard** [comment]
@JCasemajor The purpose of these thumbnails was to ensure that the scripts were developed in packages. Since then, we have implemented unit tests and ensured the reproducibility of the results with the original model. 

I propose you to pass these vignette in archive to brighten up the repo.

**Comment by JCasemajor** [comment]
Je valide.
