### ISSUE TITLE
[feat] As dev, I'd like to easily and safely export outputs of the original scripts out of the project dir

### ISSUE THREAD

**Issue by dagousket** [balglave/FishMap#9]
As dev, I'd like to easily and safely export outputs of the original scripts out of the project dir so I can create target value for future unit tests and compare with output from Clients.

## Client - Validation 

+ [x] ThinkR save covariates and outputs to use in the model in a folder outside the project, based on the original script

![Image](https://user-images.githubusercontent.com/54443785/222466085-b7856963-93d7-4051-9daf-4e8d0de0cdf9.png)

=> [https://github.com/balglave/FishMap/commit/4721111bfda98d41924c8aa937a60d569276904f#diff-7c669b130405476e22842e0725fbb6ed23edf2994abbca6a101e5bbce706b2c8](https://github.com/balglave/FishMap/commit/4721111bfda98d41924c8aa937a60d569276904f#diff-7c669b130405476e22842e0725fbb6ed23edf2994abbca6a101e5bbce706b2c8)

 `.Renvion` variables used :

![Image](https://user-images.githubusercontent.com/54443785/222469680-e3ff9bff-a9e9-4267-9cdf-101acce72939.png)

+ [x] users can reproduce output based on a seed that fix random number generation

![Image](https://user-images.githubusercontent.com/54443785/222465686-7b8557ac-6054-4b21-946c-6d86973c3780.png)

=> [https://github.com/balglave/FishMap/commit/4721111bfda98d41924c8aa937a60d569276904f#diff-8d52a6f53ef7f7b9c3829a7600b00088e8ba7fad095e9c0aae8d644728cae1c7](https://github.com/balglave/FishMap/commit/4721111bfda98d41924c8aa937a60d569276904f#diff-8d52a6f53ef7f7b9c3829a7600b00088e8ba7fad095e9c0aae8d644728cae1c7)

+ [x] a vignette is available to show how to easily launch main.R and store outputs

![Image](https://user-images.githubusercontent.com/54443785/222464917-5f42a203-1374-44f7-9991-b3538e7b10ea.png)

=> [https://balglave.github.io/FishMap/articles/execute-main.html](https://balglave.github.io/FishMap/articles/execute-main.html)

## Dev - Tech

+ [x] Define interesting outputs considering the future division of the code into flats and functions
+ [x] Define a way to store these outputs in an external folder that will be used for test

This folder `output_dir` will be used internally as a reference for our unit tests. It will be stored in a shared folder accessible by all devs and not tracked by git (output files total size is >800Mb)

+ [x] Une a env.var to decide whether or not to (over)write content of output dir

```r
if (Sys.getenv("FISHMAP_UPDATE_OUTPUTS" = "TRUE")) {# write in folder, otherwise to not save}
```

+ [x] Set a seed to reproduce model runs

```r
set.seed(1234)
Dans Renviron de chaque dev: "FISHMAP_OUTPUT_DIR=~/shared/outputs_fishmap"
output_dir <-  Sys.getenv("FISHMAP_OUTPUT_DIR")# tempfile()
dir.create(output_dir, recursive = TRUE)
source(here::here("dev/scripts_orig/main.R"))
# Nous envoyer un zip de "output_dir"
```

+ [x] keep track of execution time for each step

+ [ ] As soon as we have a reproducible script (potentially with seeds), and defined all outputs that we think we need, open an issue for the client to execute the same code as us, and give us their outputs, so that we can numerically compare

=> Validation for the next issue
+ [ ] Outputs are the same (or similar) as on clients machine
    + Client has to execute the code on themselves and gives outputs to ThinkR

**Comment by JCasemajor** [comment]
Hello,
I have an issue while running : 
[source](https://rdrr.io/r/base/source.html)(here::[here](https://here.r-lib.org//reference/here.html)("dev","run_main_and_save_output.R"))

The error is : 
Error in h(simpleError(msg, call)) :
erreur d'ï¿½valuation de l'argument 'obj' lors de la sï¿½lection d'une mï¿½thode pour la fonction 'bbox' : l'affectation d'un objet de classe “character” n'est pas permise pour le slot ‘proj4string’ dans un objet de classe “Spatial” ; is(value, "CRS") ne renvoie pas TRUE

I had this issue before and I solved it by changing crs to upper-case (CRS) in domain_mesh_spde.R line 17 and line 42 (still works). As I don't want to alter the script you made, what would you suggest I do to prevent this error ?

Otherwise, everything seems to work fine.

**Comment by statnmap** [comment]
Thanks. I open an issue for this bug: https://github.com/balglave/FishMap/issues/22

**Comment by JCasemajor** [comment]
Je valide.
