### ISSUE TITLE
As dev, i'd like to have the CI running once a month

### ISSUE THREAD

**Issue by Cervangirard** [balglave/FishMap#90]
As dev, i'd like to have the CI running once a month so that i will know if the package still works with new version of packages.

## Client - Validation 

+ [x] the CI is launched once a month on the main branch
![image](https://user-images.githubusercontent.com/37626302/231384095-d5f38135-77c1-46b3-b448-547975847e05.png)
![image](https://user-images.githubusercontent.com/37626302/231384490-648b57a2-b635-4656-88d0-445b410493aa.png)

https://github.com/balglave/FishMap/actions/runs/4675574058

## Dev - Tech

+ [x] using schedule into CI

**Comment by JCasemajor** [comment]
Je valide.

**Comment by balglave** [comment]
Je valide
